---
- hosts: web
  name: This is a Playbook
  sudo: yes

  vars:
    packages:
    - httpd
    - libselinux-python

  tasks:
  - name: stop iptables
    service: name=iptables state=stopped


  - name: start and enable apache service
    service: name=httpd state=stopped enabled=no

  - name: remove packages
    yum: name={{ item }} state=absent
    with_items: packages

  - name: delete index.html
    file: path=/var/www/html/index.html state=absent
    notify: something deleted

  handlers:
  - name: something deleted
    shell: echo "file deleted" >> /tmp/some.log
