- name: yum install commons packages (Red Hat)
  yum: name={{ item }} state=present
  with_items: packages

- name: RedHat/CentOS - Install pip
  command: bash -c "curl https://bootstrap.pypa.io/get-pip.py | python -"
  sudo: yes

- name: pip Install httplib2
  pip: name=httplib2 state=present

#- name: pip Install httplib2
#  pip: name={{ item }} state=present
#  with_items: pip-packages

- name: stop iptables
  service: name=iptables state=stopped
